# Generated by Django 3.2.9 on 2023-01-25 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Controler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet', models.CharField(default='none', max_length=10, verbose_name='Подписка')),
                ('model', models.CharField(max_length=10, verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='CreateAssembling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Устройство')),
                ('model', models.CharField(max_length=10, verbose_name='Модель')),
                ('condition', models.CharField(max_length=10, verbose_name='Состояние')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_sh', to='core.controler')),
            ],
        ),
        migrations.CreateModel(
            name='New_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=15, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=30, verbose_name='Почта')),
                ('feedback', models.CharField(max_length=5000, verbose_name='Пожелания, предложения')),
                ('grade', models.IntegerField(verbose_name='Оценка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='controler',
            name='contr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='core.new_profile'),
        ),
        migrations.CreateModel(
            name='Assembling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant', models.IntegerField()),
                ('control', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assem', to='core.controler')),
                ('creass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assem', to='core.createassembling')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assem', to='core.products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assem', to='core.new_profile', verbose_name='Пользователь')),
            ],
        ),
    ]
