# Generated by Django 3.2.9 on 2023-01-19 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfofinish',
            name='grade',
            field=models.IntegerField(max_length=5, verbose_name='Оценка'),
        ),
    ]
