# Generated by Django 3.2.9 on 2023-01-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controler',
            name='packet',
            field=models.CharField(default='none', max_length=10, verbose_name='Подписка'),
        ),
    ]
