# Generated by Django 3.2.9 on 2023-01-25 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_products_prod'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='prod',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='system_sh', to='core.controler'),
        ),
    ]
