# Generated by Django 3.2.9 on 2023-01-19 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_userinfofinish_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfofinish',
            name='feedback',
            field=models.CharField(max_length=5000, verbose_name='Пожелания, предложения'),
        ),
    ]
