# Generated by Django 3.2.9 on 2023-01-19 02:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_alter_userinfofinish_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='new_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('username', models.CharField(max_length=15, verbose_name='Имя пользователя')),
                ('email', models.EmailField(max_length=30, verbose_name='Почта')),
                ('feedback', models.CharField(max_length=5000, verbose_name='Пожелания, предложения')),
                ('grade', models.IntegerField(max_length=5, verbose_name='Оценка')),
                ('subject', models.CharField(max_length=100, verbose_name='Объект')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Userinfofinish',
        ),
    ]
