# Generated by Django 3.2.9 on 2023-01-25 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20230125_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='prod',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, related_name='system_sh', to='core.controler', verbose_name='Контроллер'),
        ),
    ]
