# Generated by Django 3.2.9 on 2023-01-19 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_new_profile_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_profile',
            name='subject',
        ),
    ]
