# Generated by Django 3.2.9 on 2023-01-21 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_new_profile_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Controler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=10, verbose_name='Модель')),
                ('data', models.DateField(max_length=10, verbose_name='Дата приобритения')),
            ],
        ),
        migrations.AddField(
            model_name='new_profile',
            name='date',
            field=models.DateField(default=0, max_length=10, verbose_name='Дата регистрации'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Устройство')),
                ('model', models.CharField(max_length=10, verbose_name='Модель')),
                ('condition', models.BooleanField(max_length=10, verbose_name='Состояние')),
                ('date_install', models.DateField(max_length=30, verbose_name='Дата установки')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.controler')),
            ],
        ),
        migrations.AddField(
            model_name='controler',
            name='controller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.new_profile'),
        ),
    ]
