# Generated by Django 3.2.9 on 2023-01-21 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230121_1017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Controler',
            new_name='core_controler',
        ),
        migrations.RenameModel(
            old_name='Products',
            new_name='core_products',
        ),
    ]
