# Generated by Django 3.2.9 on 2023-01-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230121_1037'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='core_controler',
            new_name='Controler',
        ),
        migrations.RenameModel(
            old_name='core_products',
            new_name='Products',
        ),
    ]
