# Generated by Django 3.2.9 on 2023-01-21 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230121_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='new_profile',
            name='date',
        ),
    ]
