# Generated by Django 3.2.9 on 2023-01-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_new_profile_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controler',
            name='data',
        ),
        migrations.RemoveField(
            model_name='products',
            name='date_install',
        ),
    ]
