# Generated by Django 4.1.5 on 2023-03-20 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=48, verbose_name="Титл поста")),
                ("text", models.TextField(max_length=448, verbose_name="Тело поста")),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.BooleanField(default=False, verbose_name="Опубликовать"),
                ),
                ("date_publication", models.DateTimeField(auto_now_add=True)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.new_profile",
                        verbose_name="Юзернейм",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.CharField(max_length=24, verbose_name="Категории")),
            ],
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.TextField(max_length=224, verbose_name="Коментарий"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        default="2",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smarthouseblog.blog",
                        verbose_name="К посту",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        default="2",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.new_profile",
                        verbose_name="Юзернейм",
                    ),
                ),
            ],
        ),
    ]
