# Generated by Django 4.1.5 on 2023-03-17 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_comment"),
        ("smarthouseblog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
        migrations.AddField(
            model_name="blog",
            name="username",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.new_profile",
                verbose_name="Юзернейм",
            ),
            preserve_default=False,
        ),
    ]
