# Generated by Django 4.1.5 on 2023-03-20 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smarthouseblog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                default="2",
                on_delete=django.db.models.deletion.PROTECT,
                to="smarthouseblog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="item",
            field=models.CharField(max_length=24, null=True, verbose_name="Категории"),
        ),
    ]
