# Generated by Django 4.1.5 on 2023-04-01 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "__first__"),
        ("smarthouseblog", "0002_card_blog_category_blog_price_blog_raiting_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=12, verbose_name="Номер карты")),
                (
                    "num_date",
                    models.CharField(max_length=4, verbose_name="Срок действия"),
                ),
                ("name", models.TextField(max_length=8, verbose_name="Имя")),
                ("surname", models.CharField(max_length=23, verbose_name="Фамилия")),
            ],
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ForeignKey(
                default="2",
                on_delete=django.db.models.deletion.PROTECT,
                to="smarthouseblog.category",
                verbose_name="Категория",
            ),
        ),
        migrations.AddField(
            model_name="blog",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="blog",
            name="raiting",
            field=models.FloatField(default=0, verbose_name="Рейтинг"),
        ),
        migrations.AddField(
            model_name="comments",
            name="raiting",
            field=models.IntegerField(default=0, verbose_name="Рейтинг"),
        ),
        migrations.AlterField(
            model_name="category",
            name="item",
            field=models.CharField(max_length=24, null=True, verbose_name="Категории"),
        ),
        migrations.AlterField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="smarthouseblog.blog",
                verbose_name="К посту",
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="username",
            field=models.ForeignKey(
                default="2",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.new_profile",
                verbose_name="Юзернейм",
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        related_name="product", to="smarthouseblog.blog"
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user",
                        to="core.new_profile",
                    ),
                ),
            ],
        ),
    ]
