# Generated by Django 4.1.5 on 2023-03-20 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "__first__"),
        ("smarthouseblog", "0002_blog_category_alter_category_item"),
    ]

    operations = [
        migrations.CreateModel(
            name="Raiting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raiting", models.IntegerField(verbose_name="Рейтинг")),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="Пользователь",
                        to="core.new_profile",
                    ),
                ),
            ],
        ),
    ]
