# Generated by Django 4.1.5 on 2023-03-20 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smarthouseblog", "0003_raiting"),
    ]

    operations = [
        migrations.AddField(
            model_name="raiting",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="Пост",
                to="smarthouseblog.blog",
            ),
            preserve_default=False,
        ),
    ]
