# Generated by Django 3.2.9 on 2023-04-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smarthouseblog', '0004_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.IntegerField(default=1, verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
