# Generated by Django 3.2.9 on 2023-04-04 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smarthouseblog', '0005_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
