# Generated by Django 4.1.5 on 2023-03-21 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smarthouseblog", "0005_comments_raiting"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comments",
            name="raiting",
        ),
    ]
