# Generated by Django 4.1.5 on 2023-03-21 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthouseblog", "0006_remove_comments_raiting"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="raiting",
            field=models.IntegerField(default=1, verbose_name="Рейтинг"),
            preserve_default=False,
        ),
    ]
