# Generated by Django 4.1.5 on 2023-03-21 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smarthouseblog", "0007_comments_raiting"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Raiting",
        ),
    ]
