# Generated by Django 4.1.5 on 2023-04-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthouseblog", "0007_alter_order_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="condition",
            field=models.TextField(
                default="Передано на сборку.", max_length=12, verbose_name="Cостояние"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="orders", to="smarthouseblog.blog"
            ),
        ),
    ]
