# Generated by Django 4.1.5 on 2023-04-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthouseblog", "0008_alter_order_condition_alter_order_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(
                related_name="prod_orders", to="smarthouseblog.blog"
            ),
        ),
    ]
