# Generated by Django 4.1.5 on 2023-03-21 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smarthouseblog", "0011_blog_raiting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="raiting",
            field=models.IntegerField(verbose_name="Рейтинг"),
        ),
    ]
