# Generated by Django 4.1.5 on 2023-03-21 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("smarthouseblog", "0012_alter_blog_raiting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="raiting",
            field=models.FloatField(verbose_name="Рейтинг"),
        ),
        migrations.AlterField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                default="2",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="smarthouseblog.blog",
                verbose_name="К посту",
            ),
        ),
    ]
