# Generated by Django 4.1.5 on 2023-03-28 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "__first__"),
        ("smarthouseblog", "0013_alter_blog_raiting_alter_comments_post"),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=12, verbose_name="Номер карты")),
                (
                    "num_date",
                    models.CharField(max_length=4, verbose_name="Срок действия"),
                ),
                ("name", models.TextField(max_length=8, verbose_name="Имя")),
                ("surname", models.CharField(max_length=23, verbose_name="Фамилия")),
            ],
        ),
        migrations.AlterField(
            model_name="comments",
            name="post",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="smarthouseblog.blog",
                verbose_name="К посту",
            ),
        ),
        migrations.AlterField(
            model_name="comments",
            name="username",
            field=models.ForeignKey(
                default="2",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                to="core.new_profile",
                verbose_name="Юзернейм",
            ),
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product",
                    models.ManyToManyField(
                        related_name="product", to="smarthouseblog.blog"
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usename",
                        to="core.new_profile",
                    ),
                ),
            ],
        ),
    ]
