# Generated by Django 4.1.5 on 2023-03-28 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "__first__"),
        (
            "smarthouseblog",
            "0014_card_alter_comments_post_alter_comments_username_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="price",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cart",
            name="username",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="core.new_profile",
            ),
        ),
    ]
